version: "3"
services:
  zerospend:
    image: coti/coti-node
    build: .
    command: ["java", "-jar", "zerospend/target/zerospend-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/configs/zerospend.properties"]
    ports:
      - "7040:7040"
      - "5001:5001"
      - "5002:5002"
    volumes:
      - "./configs:/configs"

  fullnode1:
    image: coti/coti-node
    command: ["java", "-jar", "fullnode/target/fullnode-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/configs/fullnode1.properties"]
    ports:
      - "7070:7070"
    volumes:
      - "./configs:/configs"

  dsp1:
    image: coti/coti-node
    command: ["java", "-jar", "dspnode/target/dspnode-0.0.1-SNAPSHOT.jar", "--spring.config.additional-location=/configs/dsp1.properties"]
    ports:
      - "8060:8060"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - "./configs:/configs"